Fix TS2345 [ERROR] when `port` option is used
This fixes an error 

```console
λ  deno cache server.ts
...
error: TS2345 [ERROR]: Argument of type '{ port: number; }' is not assignable to parameter of type 'ServerOptions'.
  Object literal may only specify known properties, and 'port' does not exist in type 'ServerOptions'.
serve({ port: 8000 })
```